version: "3.8"

services:
  webhookapi:
    build:
      context: .
      dockerfile: WebhookApi/Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
    networks:
      - webhook-network
networks:
  webhook-network:
    driver: bridge

volumes:
