version: "3.8"

services:
  webhookapi:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: emmanueljomer/webhookapi:latest
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./appsettings.Production.json:/app/appsettings.Production.json:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__HostName=rabbitmq
    restart: unless-stopped
    networks:
      - webhook-network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - webhook-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  webhook-network:
    driver: bridge

volumes:
  rabbitmq_data:
